# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19HpbVlgO0Px6lYMpouSoAkQ1Q16zhzms
"""

class AgentBase:
    def __init__(self, name):
        self.name = name

    def run(self, data):
        raise NotImplementedError("Each agent must implement its own run method.")