# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19HpbVlgO0Px6lYMpouSoAkQ1Q16zhzms
"""

class HealthMonitoringAgent(AgentBase):
    def run(self, health_df):
        def analyze(row):
            alerts = []
            if row["Heart Rate Below/Above Threshold (Yes/No)"] == "Yes":
                alerts.append("Heart Rate Alert")
            if row["Blood Pressure Below/Above Threshold (Yes/No)"] == "Yes":
                alerts.append("Blood Pressure Alert")
            if row["Glucose Levels Below/Above Threshold (Yes/No)"] == "Yes":
                alerts.append("Glucose Alert")
            if row["SpO₂ Below Threshold (Yes/No)"] == "Yes":
                alerts.append("Low SpO₂")
            return alerts if alerts else ["Normal"]

        health_df["Health Alerts"] = health_df.apply(analyze, axis=1)
        return health_df