# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19HpbVlgO0Px6lYMpouSoAkQ1Q16zhzms
"""

class ReminderAgent(AgentBase):
    def run(self, reminder_df):
        def evaluate(row):
            if row["Reminder Sent (Yes/No)"] == "Yes" and row["Acknowledged (Yes/No)"] == "No":
                return "Ignored"
            elif row["Reminder Sent (Yes/No)"] == "No":
                return "Not Sent"
            return "Acknowledged"

        reminder_df["Reminder Status"] = reminder_df.apply(evaluate, axis=1)
        return reminder_df