# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19HpbVlgO0Px6lYMpouSoAkQ1Q16zhzms
"""

class SafetyMonitoringAgent(AgentBase):
    def run(self, safety_df):
        def check(row):
            if row["Fall Detected (Yes/No)"] == "Yes" or row["Post-Fall Inactivity Duration (Seconds)"] > 60:
                return "Safety Alert"
            return "Safe"

        safety_df["Safety Status"] = safety_df.apply(check, axis=1)
        return safety_df